### ISSUE TITLE
Production Issues

### ISSUE THREAD

**Issue by elliottneilclark** [batteries-included/batteries-included#1013]
- [x] Signup emails use 127.0.0.1
- [x] Installation to control server links don't work.  Go to our [int-prod install show page](https://home-base.battery-traditional.webapp.13-59-225-158.batrsinc.co/installations/batt_0191f28be0a4764bbd13602aa4411a69) and click the "Control Server Button" it sends you to: http://control.13-59-225-158.batrsinc.co/ It should send you to: https://control.13-59-225-158.batrsinc.co
- [x] The home dashboard should always show something inviting you to start an installation
- [x] Placeholder for trimmed video #1019

**Comment by JTarasovic** [comment]
control server links fixed.

**Comment by jsonmaur** [comment]
Home dashboard fixed by https://github.com/batteries-included/batteries-included/pull/1017
