### ISSUE TITLE
We shouldn't tag latest on tab builds

### ISSUE THREAD

**Issue by elliottneilclark** [batteries-included/batteries-included#1119]
For tag pushes we shouldn't include the latest tag. There is almost always a newer build that's "latest"

**Comment by elliottneilclark** [comment]
Maybe it did the right thing?

https://github.com/batteries-included/batteries-included/actions/runs/11521195242/job/32074277579

```
echo "ADDITIONAL_TAGS=latest" >> "$GITHUB_ENV"
```

Is run. But it looks like latest is on 0.30.0-aeb8099

**Comment by JTarasovic** [comment]
Yeah, that change should push latest on master and tag on tag.
