### ISSUE TITLE
monitoring: better tuning of storage defaults

### ISSUE THREAD

**Issue by JTarasovic** [batteries-included/batteries-included#1176]
We use 1GB and 5GB volumes for vm_{select,storage} respectively with a 1month (default) retention.

We should scale the storage and retention with the cluster size?

```
 -retentionPeriod value
     Data with timestamps outside the retentionPeriod is automatically deleted. The minimum retentionPeriod is 24h or 1d. See also -retentionFilter
     The following optional suffixes are supported: s (second), h (hour), d (day), w (week), y (year). If suffix isn't set, then the duration is counted in months (default 1)
```

**Comment by elliottneilclark** [comment]
While you're doing this we should also make sure that the volume sizes are in integers when stored so that I can put a slider on it for the ui.
