### ISSUE TITLE
Home base all-in-one installation script

### ISSUE THREAD

**Issue by jsonmaur** [batteries-included/batteries-included#536]
We need an all-in-one bash/curl installation script to install the control server in a selected provider. This should be generated for each installation based on the provider and usage environment. Replace `https://install.example.com/8ej3l` in `HomeBaseWeb.InstallationShowLive` with the real script once it's ready.

There should also be a way for home base to detect whether the remote installation is up and running or not. If it's not, the installation instructions and script are shown on the installation page (see the `:installed?` attribute in `HomeBaseWeb.InstallationShowLive`). If it is, we should display a link to the control server.

Related to https://github.com/batteries-included/batteries-included/pull/532.

**Comment by elliottneilclark** [comment]
The page http://home.127-0-0-1.batrsinc.co:4100/installations/batt_0192160315397ce5be59e8d24df2a425

will also need it's URL updated.
