### ISSUE TITLE
Installation page should show latest reports

### ISSUE THREAD

**Issue by elliottneilclark** [batteries-included/batteries-included#885]
For pages like: http://home.127-0-0-1.batrsinc.co:4100/installations/batt_0192160315397ce5be59e8d24df2a425

- [x] Only show the installation instructions if there are no usage reports
- [x] If there are host reports then show links to the control server and other installed batteries.
- [x] If there's usage report then show how many nodes, pods, and batteries.

**Comment by JTarasovic** [comment]
We can add more stuff as needed but I think I've got the three things in this issue covered.
