### ISSUE TITLE
Actions not running for merged dependabot commits

### ISSUE THREAD

**Issue by elliottneilclark** [batteries-included/batteries-included#901]
We aren't building images for dependabot commits. So since that was the last commit of 0.18.1 we don't have that docker image built. :-/

**Comment by JTarasovic** [comment]
Do we want to build images for those then? Or do something different like push new images on tag?

**Comment by elliottneilclark** [comment]
We should run all the GitHub actions for every commit on master.

**Comment by JTarasovic** [comment]
> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.

I'm pretty sure this :point_up: is the issue.
