### ISSUE TITLE
Email Format

### ISSUE THREAD

**Issue by elliottneilclark** [batteries-included/batteries-included#912]
There are some formatting issues with email:

- We should try and use assets from static site. Currently the heading image isn't there.
- The address at the end is wrong. I dont' think we really want to include an address in every email.\
- Emails don't use the correct URL for home.

**Comment by jsonmaur** [comment]
Having a physical address in the footer helps prevent the message being marked as spam. But I think that may only be necessary for promotional/marketing emails, not transactional emails. Will look into this further.

**Comment by elliottneilclark** [comment]
TIL https://www.ftc.gov/business-guidance/resources/can-spam-act-compliance-guide-business

> doesn’t apply just to bulk email. It covers all commercial messages, which the law defines as “any electronic mail message the primary purpose of which is the commercial advertisement or promotion of a commercial product or service,” including email that promotes content on commercial websites. 



The Delaware C corp is located at:

8 THE GREEN, STE B
DOVER
DE
19901
